---
title: "MP2"
author: "Haley Schmidt"
date: "9/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
scbi_stem1 <- read_csv("tree_main_census/data/census-csv-files/scbi.stem1.csv")
scbi_stem2 <- read_csv("tree_main_census/data/census-csv-files/scbi.stem2.csv")
scbi_stem3 <- read_csv("tree_main_census/data/census-csv-files/scbi.stem3.csv")
```

```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
```

```{r}
stem1 <- scbi_stem1 %>%
  filter(dbh != "NULL") %>%
  mutate(dbh = as.numeric(dbh)) %>%
  select(sp, dbh, CensusID) %>%
  group_by(sp) %>% 
  summarize(avg_dbh_sp = mean(dbh),
            census_year = mean(CensusID))

stem2 <- scbi_stem2 %>%
  filter(dbh != "NULL") %>%
  mutate(dbh = as.numeric(dbh)) %>%
  select(sp, CensusID, dbh) %>%
  group_by(sp) %>% 
  summarize(avg_dbh_sp = mean(dbh),
            census_year = mean(CensusID))

stem3 <- scbi_stem3 %>%
  filter(dbh != "NULL") %>%
  mutate(dbh = as.numeric(dbh)) %>%
  select(sp, CensusID, dbh) %>%
  group_by(sp) %>% 
  summarize(avg_dbh_sp = mean(dbh),
            census_year = mean(CensusID))

stem_joined <- rbind(stem1, stem2, stem3)

genus_dbh <- stem_joined %>%
  inner_join(scbi_spptable, by = "sp") %>%
  select(Genus, avg_dbh_sp, census_year) %>%
  group_by(Genus, census_year) %>%
  summarize(avg_dbh = mean(avg_dbh_sp))
View(genus_dbh)

year.labs <- c("2008", "2013", "2018")
names(year.labs) <- c("1", "2", "3")

ggplot(data = genus_dbh, mapping = aes(x = Genus, y = avg_dbh))+
  geom_bar(color = "white", fill = "darkgreen", stat='identity')+
  facet_wrap(~census_year, labeller = labeller(census_year = census_year.labs))+
  labs(title = "Average DBH for Each Genus in the SCBI Census", x = "Genus", y = "Average DBH")+
  theme(axis.text.x=element_text(angle = 90, size = 5))
  
```

```{r}
stem1 <- scbi_stem1 %>%
  filter(dbh != "NULL") %>%
  mutate(dbh = as.numeric(dbh)) %>%
  select(sp, dbh, CensusID) %>%
  group_by(sp) %>% 
  summarize(avg_dbh_sp = mean(dbh),
            census_year = mean(CensusID))

stem2 <- scbi_stem2 %>%
  filter(dbh != "NULL") %>%
  mutate(dbh = as.numeric(dbh)) %>%
  select(sp, CensusID, dbh) %>%
  group_by(sp) %>% 
  summarize(avg_dbh_sp = mean(dbh),
            census_year = mean(CensusID))

stem3 <- scbi_stem3 %>%
  filter(dbh != "NULL") %>%
  mutate(dbh = as.numeric(dbh)) %>%
  select(sp, CensusID, dbh) %>%
  group_by(sp) %>% 
  summarize(avg_dbh_sp = mean(dbh),
            census_year = mean(CensusID))

stem_joined <- rbind(stem1, stem2, stem3)

genus_dbh <- stem_joined %>%
  inner_join(scbi_spptable, by = "sp") %>%
  select(Genus, avg_dbh_sp, census_year) %>%
  group_by(Genus, census_year) %>%
  summarize(avg_dbh = mean(avg_dbh_sp))

year.labs <- c("2008", "2013", "2018")
names(year.labs) <- c("1", "2", "3")

ggplot(data = genus_dbh, mapping = aes(x = Genus, y = avg_dbh, fill = census_year))+
  geom_bar(color = "white", stat='identity')+
  labs(title = "Average DBH for Each Genus in the SCBI Census", subtitle = "dark blue: 2008        medium blue: 2013        light blue: 2018", x = "Genus", y = "Average DBH")+
  theme(axis.text.x=element_text(angle = 90, size = 9), legend.position = "none")
```

