---
title: "MP2_EDA"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE}
library(tidyverse)
library(lubridate)
library(ggplot2)
theme_set(
  theme_light() + theme(legend.position = "top")
  )
```

```{r, warning = FALSE}
stem1 <- read_csv("../tree_main_census/data/census-csv-files/scbi.stem1.csv")
stem2 <- read_csv("../tree_main_census/data/census-csv-files/scbi.stem2.csv")
stem3 <- read_csv("../tree_main_census/data/census-csv-files/scbi.stem3.csv")
spptable <- read_csv("../tree_main_census/data/census-csv-files/scbi.spptable.csv")
```

```{r, warning = FALSE}
full <- rbind(stem1, stem2, stem3) %>%
  mutate(ExactDate = lubridate::mdy(ExactDate),
         DFstatus = as.factor(DFstatus),
         dbh = as.numeric(dbh))

alive <- full %>% 
  filter(DFstatus == "alive")

other <- full %>% 
  filter(DFstatus != "alive")
```

```{r, warning = FALSE}
facet_labels <- c(`1` = "Census 1 in 2008-2010", `2` = "Census 2 in 2013", `3` = "Census 3 in 2018")
  
alive %>% ggplot(aes(dbh)) +
  geom_histogram() +
  facet_wrap(~CensusID, labeller = labeller(CensusID = facet_labels)) +
  labs(x = "Diameter at breast height (dbh)", y = "number of trees", 
       title = "Histogram of tree heights", 
       subtitle = "(for alive trees only)")

other %>% ggplot(aes(dbh)) +
  geom_histogram() +
  facet_wrap(~CensusID, labeller = labeller(CensusID = facet_labels)) +
  labs(x = "Diameter at breast height (dbh)", y = "number of trees", 
       title = "Histogram of tree heights", 
       subtitle = "(for non-alive trees)")
```